name: Build and Publish

on:
  push:
    branches: ["master"]

jobs:
  if_pushed_build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Java version
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven Image
        run: mvn -DskipTests package

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/si:si-api

      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/si:si-api
